const COMPILER_EOFOL_TAG_DEFAULT = "e"

const COMPILER_EOFOL_TAGS = [COMPILER_EOFOL_TAG_DEFAULT, "eofol"]

const COMPILER_STATEFUL_WRAPPER_TAG = "div"

module.exports = { COMPILER_EOFOL_TAG_DEFAULT, COMPILER_EOFOL_TAGS, COMPILER_STATEFUL_WRAPPER_TAG }
