const { COMPILATION_VERBOSE, COMPILATION_SHOW_PROGRESS } = require("../config")

const pluginName = "eofol4-compiler"

const VERBOSE = COMPILATION_VERBOSE === "true" || COMPILATION_VERBOSE === true
const VERBOSE_INFO = true
const VERBOSE_OPTIMIZE_ASSETS = false
const PROGRESS = COMPILATION_SHOW_PROGRESS === "true" || COMPILATION_SHOW_PROGRESS === true
const PROGRESS_OPTIMIZE_ASSETS = PROGRESS && VERBOSE_OPTIMIZE_ASSETS

const SERVICE_WORKER_PAGES_PLACEHOLDER = '"@@VIEWS@@"'

module.exports = {
  pluginName,
  VERBOSE,
  VERBOSE_INFO,
  PROGRESS,
  PROGRESS_OPTIMIZE_ASSETS,
  SERVICE_WORKER_PAGES_PLACEHOLDER,
}
