import { f } from "./create-element"

export const div = f("div")
export const span = f("span")

export const p = f("p")
export const h1 = f("h1")
export const h2 = f("h2")
export const h3 = f("h3")
export const h4 = f("h4")
export const h5 = f("h5")
export const h6 = f("h6")
export const a = f("a")
export const code = f("code")
export const pre = f("pre")
export const sub = f("sub")
export const sup = f("sup")

export const button = f("button")
export const input = f("input")
export const textarea = f("textarea")
export const label = f("label")

export const img = f("img")

export const ol = f("ol")
export const ul = f("ul")
export const li = f("li")

export const table = f("table")
export const th = f("th")
export const tr = f("tr")
export const td = f("td")
export const thead = f("thead")
export const tbody = f("tbody")
export const tfoot = f("tfoot")

export const progress = f("progress")
export const form = f("form")
export const select = f("select")
export const option = f("option")

export const style = f("style")
export const linkTag = f("link")
export const script = f("script")
export const noscript = f("noscript")

export const html = f("html")
export const body = f("body")
export const head = f("head")

export const meta = f("meta")
export const title = f("title")

export const article = f("article")
export const aside = f("aside")
export const details = f("details")
export const figcaption = f("figcaption")
export const figure = f("figure")
export const footer = f("footer")
export const header = f("header")
export const main = f("main")
export const mark = f("mark")
export const nav = f("nav")
export const section = f("section")
export const summary = f("summary")
export const time = f("time")
